language: python
python:
  - "3.7"

install: "pip install -r requirements.txt pre-commit"

jobs:
  include:
    - python: 3.7
      stage: test

script:
  - pre-commit run --all-files
  - pytest tests -vv

cache:
  directories:
    - $HOME/.cache/pre-commit
    - $HOME/.cache/pip
